apiVersion: v1
kind: Namespace
metadata:
  creationTimestamp: null
  name: helloworld
spec: {}
status: {}
---
apiVersion: v1
kind: Namespace
metadata:
  creationTimestamp: null
  name: windows
spec: {}
status: {}
